# Car Data

## Columns:

**General Columns** 
- url: url of autos 
- short_description, description: Description of autos (in English and German) written by users 

**Categorical Columns**  
- make_model, make, model: Model of autos. Ex:Audi A1 
- body_type, body: Body type of autos Example: van, sedans * vat: VAT deductible, price negotiable 
- registration, first_registration: First registration date and year of autos. 
- prev_owner, previous_owners: Number of previous owners * type: new or used 
- next_inspection, inspection_new: information about inspection (inspection date,..) 
- body_color, body_color_original: Color of auto Ex: Black, red * paint_type: Paint type of auto Ex: Metallic, Uni/basic 
- upholstery: Upholstery information (texture, color) 
- gearing_type: Type of gear Ex: automatic, manual 
- fuel : fuel type Ex: diesel, benzine 
- co2_emission, emission_class, emission_label: emission information 
- drive_chain: drive chain Ex: front,rear, 4WD 
- consumption: consumption of auto in city, country and combination (lt/100 km) 
- country_version 
- entertainment_media 
- safety_security 
- comfort_convenience 
- extras 

**Quantitative Columns**
- price: Price of cars 
- km: km of autos 
- hp: horsepower of autos (kW) 
- displacement: displacement of autos (cc) 
- warranty: warranty period (month) 
- weight: weight of auto (kg) 
- nr_of_doors: number of doors 
- nr_of_seats : number of seats 
- cylinders: number of cylinders 
- gears: number of gears

In [172]:
import numpy as np
import pandas as pd

scout_car_data = pd.read_json('scout_car.json', lines=True)
scout_car_data.columns = scout_car_data.columns.str.lower().str.replace(' ', '_').str.replace('.', '')
scout_car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   make_model                     15919 non-null  object
 2   short_description              15873 non-null  object
 3   body_type                      15859 non-null  object
 4   price                          15919 non-null  int64
 5   vat                            11406 non-null  object
 6   km                             15919 non-null  object
 7   registration                   15919 non-null  object
 8   prev_owner                     9091 non-null   object
 9   kw                             0 non-null      float64
 10  hp                             15919 non-null  object
 11  type                           15917 non-null  object
 12  previous_owners                9279 non-null   object
 13  next_inspection                3535 non-null   object
 14  inspection_new                 3932 non-null   object
 15  warranty                       10499 non-null  object
 16  full_service                   8215 non-null   object
 17  non-smoking_vehicle            7177 non-null   object
 18  null                           15919 non-null  object
 19  make                           15919 non-null  object
 20  model                          15919 non-null  object
 21  offer_number                   12744 non-null  object
 22  first_registration             14322 non-null  object
 23  body_color                     15322 non-null  object
 24  paint_type                     10147 non-null  object
 25  body_color_original            12160 non-null  object
 26  upholstery                     12199 non-null  object
 27  body                           15859 non-null  object
 28  nr_of_doors                    15707 non-null  object
 29  nr_of_seats                    14942 non-null  object
 30  model_code                     4978 non-null   object
 31  gearing_type                   15919 non-null  object
 32  displacement                   15423 non-null  object
 33  cylinders                      10239 non-null  object
 34  weight                         8945 non-null   object
 35  drive_chain                    9061 non-null   object
 36  fuel                           15919 non-null  object
 37  consumption                    14013 non-null  object
 38  co2_emission                   14111 non-null  object
 39  emission_class                 12898 non-null  object
 40
comfort_&_convenience
        14999 non-null  object
 41
entertainment_&_media
        14545 non-null  object
 42
extras
                       12957 non-null  object
 43
safety_&_security
            14937 non-null  object
 44  description                    15919 non-null  object
 45  emission_label                 3985 non-null   object
 46  gears                          11207 non-null  object
 47  country_version                7586 non-null   object
 48  electricity_consumption        137 non-null    object
 49  last_service_date              566 non-null    object
 50  other_fuel_types               880 non-null    object
 51  availability                   635 non-null    object
 52  last_timing_belt_service_date  16 non-null     object
 53  available_from                 272 non-null    object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB

In [173]:
#km.value_counts(dropna=False)

## Quantitative Columns
- [x] price: Price of cars 
- [x] km: km of autos 
- [x] hp: horsepower of autos (kW) 
- [x] displacement: displacement of autos (cc) 
- [] warranty: warranty period (month) (drop?)
- [x] weight: weight of auto (kg) 
- [x] nr_of_doors: number of doors 
- [x] nr_of_seats : number of seats 
- [x] cylinders: number of cylinders 
- [x] gears: number of gears

### price

In [174]:
scout_car_data['price'].astype("float")
scout_car_data[['price']].sample(5)

       price
9456    8900
9661   14699
9486   14350
5748   15950
11066  12450

### km

In [175]:
scout_car_data['km'] = scout_car_data['km'].str.replace(',', '').str.findall('\d+').str[0].astype("float")
scout_car_data[['km']].sample(5)

            km
5179    5000.0
12067  33660.0
4712    9500.0
594    70017.0
9837   43000.0

### hp

In [176]:
scout_car_data['hp'] = scout_car_data['hp'].str.replace(',', '').str.findall('\d+').str[0].astype("float")
scout_car_data[['hp']].sample(5)

          hp
15171  118.0
12372  100.0
9827    74.0
410     66.0
1575    85.0

### displacement

In [177]:
scout_car_data['displacement'] = scout_car_data['displacement'].str[0].str.replace(',', '').str.findall('\d+').str[0].astype("float")
scout_car_data[['displacement']].sample(5)

       displacement
8826         1248.0
13180        1197.0
1631          999.0
6405         1598.0
13420        1197.0

### weight

In [178]:
scout_car_data['weight'] = scout_car_data['weight'].str[0].str.replace(',', '').str.findall('\d+').str[0].astype("float")
scout_car_data[['weight']].sample(5)

       weight
12302  2000.0
345       NaN
12843  1560.0
7527   1360.0
6191      NaN

### nr_of_doors

In [179]:
scout_car_data['nr_of_doors'] = scout_car_data['nr_of_doors'].str[0].str.findall('\d+').str[0]
scout_car_data[['nr_of_doors']].sample(5)

      nr_of_doors
2439            5
2995            5
8533          NaN
13137           5
12714           5

### nr_of_seats

In [180]:
scout_car_data['nr_of_seats'] = scout_car_data['nr_of_seats'].str[0].str.findall('\d+').str[0]
scout_car_data[['nr_of_seats']].sample(5)

      nr_of_seats
13979           2
15074           7
8383            5
3492            5
15832           5

### cylinders

In [186]:
scout_car_data['cylinders'] = scout_car_data['cylinders'].str[0].str.findall('\d+').str[0]
scout_car_data[['cylinders']].sample(5)

      cylinders
6019          4
10307       NaN
829           3
4494          4
1375          3

### gears

In [187]:
scout_car_data['gears'] = scout_car_data['gears'].str[0].str.findall('\d+').str[0]
scout_car_data[['gears']].sample(5)

      gears
1899      7
9673    NaN
8441      6
13443     5
320     NaN